Repository FE-DeepDive/JavaScript-DeepDive, pull requests merged in 2022-09, with the labels that each got.

#5 [✏️ Docs] <Assignment> 이슈 템플릿 추가, Docs 이슈 템플릿 중복 내용 수정, PR Template 추가
  .github/ISSUE_TEMPLATE/---docs.md
  .github/ISSUE_TEMPLATE/--assignment.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✏️ docs, ✨ proposal

#7 docs: 깃 전략 과제 완료
  JavaScript/5주차/assignment/재영/test.md
Labels: ✏️ docs

#8 docs:깃 관리 실습
  JavaScript/5주차/assignment/정희/test.md
Labels: ✏️ docs

#9 docs: 깃과제 하는중
  JavaScript/5주차/assignment/민혜/test.md
Labels: ✏️ docs

#10 docs: git 관리 테스트
  JavaScript/5주차/assignment/예진/git.md
Labels: ✏️ docs

#13 [Assignment] 재영 - Caculator 구현
  .vscode/settings.json
  JavaScript/6주차/assignment/재영/index.js
Labels: ✅ Assignment

#14 [Assignment] 민혜 - Caculator 구현
  JavaScript/6주차/assignment/민혜/index.js
Labels: ✅ Assignment
